version: '3'

tasks:
  clean:
    cmds:
      - rm -rf dist
  build:
    label: build-{{.TASK}}
    vars:
      VERSION:
        sh: git symbolic-ref -q --short HEAD || git describe --tags --exact-match
      BUILD_COMMIT:
        sh: git rev-parse HEAD
      BUILD_DATE:
        sh: date "+%F %T"
    cmds:
      - |
        GOOS={{.GOOS}} GOARCH={{.GOARCH}} GOARM={{.GOARM}} GOMIPS={{.GOMIPS}} \
        go build -trimpath -o dist/gitflow-toolkit-{{.TASK}} -ldflags \
        "-w -s -X main.version={{.VERSION}} -X main.buildCommit={{.BUILD_COMMIT}} -X 'main.buildDate=${BUILD_DATE}'"
  linux-386:
    cmds:
      - task: build
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: 386
        }
  linux-amd64:
    cmds:
      - task: build
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: amd64
        }
  linux-amd64-v3:
    cmds:
      - task: build
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: amd64,
          GOAMD64: v3
        }
  linux-armv5:
    cmds:
      - task: build
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: arm,
          GOARM: 5
        }
  linux-armv6:
    cmds:
      - task: build
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: arm,
          GOARM: 6
        }
  linux-armv7:
    cmds:
      - task: build
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: arm,
          GOARM: 7
        }
  linux-arm64:
    cmds:
      - task: build
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: arm64
        }
  darwin-amd64:
    cmds:
      - task: build
        vars: {
          TASK: "{{.TASK}}",
          GOOS: darwin,
          GOARCH: amd64
        }
  darwin-arm64:
    cmds:
      - task: build
        vars: {
          TASK: "{{.TASK}}",
          GOOS: darwin,
          GOARCH: arm64
        }
  default:
    cmds:
      - task: clean
      - task: linux-386
      - task: linux-amd64
      - task: linux-amd64-v3
      - task: linux-armv5
      - task: linux-armv6
      - task: linux-armv7
      - task: linux-arm64
      - task: darwin-amd64
      - task: darwin-arm64
